  0.000000E+00  0.000000E+00  0.000000E+00  true
    54
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0    27 false  true
     0    26 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
     0     0 false false
